### PR TITLE
Add new social channels

### PR DESCRIPTION
**Pull request by yavuzKomecoglu**
Issue #176 development completed.
The svg code sources of the added icons are taken from below.
- [Instagram SVG Icon Code](https://fontawesomeicons.com/svg/icons/instagram)
- [Blog Medium SVG Icon Code](https://fontawesomeicons.com/svg/icons/medium)
- [Linkedin SVG Icon Code](https://fontawesomeicons.com/svg/icons/linkedin)
- [Twitter SVG Icon Code](https://fontawesomeicons.com/svg/icons/twitter) (Can also be replaced with Twitter new 'X' logo 😄 )

Unfortunately, I did not have the opportunity to stand up and test the project locally.
I made the necessary edits in HTML. Hopefully it will not be a problem.

### CODE REVIEW

**Comment by enderahmetyurt** [comment]
thank you very much @yavuzKomecoglu. Could you share a screen share of your development?

**Comment by yavuzKomecoglu** [comment]
> thank you very much @yavuzKomecoglu. Could you share a screen share of your development?

I just tested it on a blank html to check that the svg's are displayed properly and their size. Screenshot: https://ibb.co/7C42NCW

**Comment by kiliczsh** [comment]
I will take care of test pipeline asap, sorry for delay :|

**Comment by enderahmetyurt** [comment]
could you centerize them?

**Comment by yavuzKomecoglu** [comment]
> could you centerize them? @yavuzKomecoglu Screenshot 2023-07-28 at 17 49 30

It's all completed though. Thanks for the merge.

**Pull request merged**
